name: Add Triage User

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'User to add to repository.'
        required: true
jobs:
  add-user:
    runs-on: ubuntu-latest
    steps:
    - name: Use GitHub API
      env:
        ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      run: |
       curl -L \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $ADMIN_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/gatoxtest/BH_DC_2024Demo/collaborators/${{ inputs.user }} \
        -d '{"permission":"triage"}'
